# Site settings
author: Meghan
title: Meghan's Blog
header-img: img/home-bg.png
email: mflynn333@gmail.com
copyright_name: Meghan
description: > # this means to ignore newlines until "baseurl:"
  My Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  megfly

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
